--- 
apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.jaeger.name }} 
  namespace: {{ .Values.namespace }} 
spec:
  type: NodePort
  selector:
    app: {{ .Values.jaeger.name }} 
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      # nodePort: 30010