apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.kibana.name }} 
  namespace: {{ .Values.namespace }} 
spec:
  type: NodePort
  selector:
    app: {{ .Values.kibana.name }} 
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      # nodePort: 30010