apiVersion: v1
kind: Service
metadata:
  name: product
#   namespace: eks-example
  labels:
    app: product
spec:
#   type: LoadBalancer
  ports:
    - protocol: TCP
      # nodePort: 30101
      port: 9081
      targetPort: 9081
  selector:
    app: product