apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.product.name }}
  namespace: {{ .Values.namespace }}
#   namespace: eks-example
  labels:
    app: {{ .Values.product.name }}
spec:
#   type: LoadBalancer
  ports:
    - protocol: TCP
      # nodePort: 30101
      port: 9081
      targetPort: 9081
  selector:
    app: {{ .Values.product.name }}