 {{- range .Values.containers }}  
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ .name }}
spec:
  type: {{.serviceType}}
  ports:
    - protocol: TCP
      # nodePort: 30101
      port: {{ .port }}
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
---    
{{- end }}     