apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jaeger.name }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.jaeger.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.jaeger.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.jaeger.name }} 
    spec:
      containers:
        - name: {{ .Values.jaeger.name }} 
          image: {{ .Values.jaeger.image }} 
          env: 
            - name: cluster.name
              value: k8s-elastic-cluster
            - name: discovery.type
              value: single-node
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"                             
      
          ports:
          
          - containerPort: 5775            
            protocol: UDP 
          - containerPort: 6831            
            protocol: UDP  
          - containerPort: 6832            
            protocol: UDP 
          - containerPort: 5778            
            protocol: TCP 
          - containerPort: 16686            
            protocol: TCP  
          - containerPort: 14268            
            protocol: TCP    
          - containerPort: 14250            
            protocol: TCP  
          - containerPort: 9411            
            protocol: TCP                                                          