apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kibana.name }} 
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.kibana.name }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kibana.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.kibana.name }} 
    spec:
      containers:
        - name: {{ .Values.kibana.name }} 
          image: {{ .Values.kibana.image }} 
          env: 
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef: 
                  name: e-commerce-logging-map
                  key: kibanaEsUrls 
          ports:
          - containerPort: 5601