# Release-wide Values
replicas: 1
version: "latest"
namespace: default
readinessUrl: /actuator/health/readiness
livenessUrl: /actuator/health/liveness
enableProbes: false
env:
  - name: zipKinUrl
    configMapKey: e-commerce-configmap
    envKey: zipkin_url

  - name: appProfile
    configMapKey: e-commerce-configmap
    envKey: SPRING_PROFILES_ACTIVE

  - name: dbUser
    configMapKey: e-commerce-secret
    envKey: db_user
    secret: true

  - name: dbPwd
    configMapKey: e-commerce-secret
    envKey: db_pwd
    secret: true

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

readinessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 300
  failureThreshold: 3

# Service Specific Values
containers:
  - name: e-commerce-gateway
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-gateway-service-secure
    enableProbes: false
    port: 9080
    serviceType: NodePort
    env:
      - name: priceUrl
        configMapKey: e-commerce-configmap
        envKey: price_url

      - name: sellerUrl
        configMapKey: e-commerce-configmap
        envKey: seller_url

      - name: productUrl
        configMapKey: e-commerce-configmap
        envKey: product_url

      - name: audienceId
        configMapKey: e-commerce-configmap
        envKey: audience_id

      - name: jwtIssuerUri
        configMapKey: e-commerce-configmap
        envKey: jwt_issuer_uri               

  - name: product-price
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-price-service
    port: 9082
    # serviceType: NodePort
    enableProbes: false
    env:
      - name: 'productPriceDbUrl'
        configMapKey: e-commerce-configmap
        envKey: db_url

      - name: 'productPriceDb'
        configMapKey: e-commerce-configmap
        envKey: db_name

  - name: product-seller
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-seller-service
    port: 9083
    # serviceType: NodePort
    enableProbes: false
    env:
      - name: 'productSellerDbUrl'
        configMapKey: e-commerce-configmap
        envKey: db_url

      - name: 'productSellerDb'
        configMapKey: e-commerce-configmap
        envKey: db_name  

  - name: product
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-service
    port: 9081
    # serviceType: NodePort
    enableProbes: false
    env:
      - name: 'productDbUrl'
        configMapKey: e-commerce-configmap
        envKey: db_url

      - name: 'productDb'
        configMapKey: e-commerce-configmap
        envKey: db_name   

  - name: e-commerce-ang
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-ang
    port: 80
    serviceType: NodePort
    enableProbes: false
    env:
      - name: apiGatewayUrl
        configMapKey: e-commerce-configmap
        envKey: api_gateway_url

      - name: authDomain
        configMapKey: e-commerce-configmap
        envKey: authDomain

      - name: clientId
        configMapKey: e-commerce-configmap
        envKey: clientId

      - name: audienceId
        configMapKey: e-commerce-configmap
        envKey: audienceId                        

ingress:
  name: e-commerce-ing-service
  replicaCount: 1
  annotations:
    class: nginx
  hosts:
    - paths:
        - path: /
          backend:
            serviceName: e-commerce-ang
            servicePort: 80
