# Release-wide Values
replicas: 1
version: 'latest'

# Service Specific Values
EcommerceGateway:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-gateway-service
ProductPrice:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-price-service
ProductSeller:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-seller-service
Product:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-service  
EcommerceAng:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-ang 