# Release-wide Values
replicas: 1
version: 'latest'
namespace: default

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}  

# Service Specific Values
e_commerce_gateway:
  name: e-commerce-gateway
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-gateway-service
product_price:
  name: product-price
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-price-service
product_seller:
  name: product-seller
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-seller-service
product:
  name: product
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-service  
e_commerce_ang:
  name: e-commerce-ang
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-ang

ingress:
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - paths: 
        - path: /
          backend:
            serviceName: e-commerce-ang
            servicePort: 80