# Release-wide Values
replicas: 1
version: 'latest'

# Service Specific Values
e_commerce_gateway:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-gateway-service
product_price:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-price-service
product_seller:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-seller-service
product:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-service  
e_commerce_ang:
  image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-ang 