version: "3.7"
services:
  product-seller-service:
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-seller-service:latest
    ports:
      - 9083:9083
    networks:
      - e-commerce-network
    restart: no

  product-price-service:
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-price-service:latest

    ports:
      - 9082:9082
    networks:
      - e-commerce-network
    restart: no

  product-service:
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
    restart: no
    ports:
      - 9081:9081
    networks:
      - e-commerce-network

  e-commerce-gateway-service:
    depends_on:
      - product-price-service
      - product-seller-service
      - product-service
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-gateway-service:latest
    # restart: always
    restart: no
    ports:
      - 9080:9080
    environment:
      price_url: http://product-price-service:9082/productPrice/product
      seller_url: http://product-seller-service:9083/productSeller/product
      product_url: http://product-service:9081/products
    networks:
      - e-commerce-network      

  e-commerce-ang-ui-service:
    depends_on:
      - e-commerce-gateway-service
    image: 337901474843.dkr.ecr.us-east-1.amazonaws.com/e-commerce-ang:latest
    environment:
      price_api_url: http://e-commerce-gateway-service:9080/price
      seller_api_url: http://e-commerce-gateway-service:9080/seller
      product_api_url: http://e-commerce-gateway-service:9080/products
    ports:
      - 4200:80
    networks:
      - e-commerce-network
    # restart: on-failure
    restart: no    

networks:
  e-commerce-network:
    driver: bridge
