server:
  port: 9086
  servlet:
    session:
      timeout: 1200
spring:
  cache:
    type: redis
  redis:
    namespace: 'e-commerce:cart' # Namespace for keys used to store sessions.
    flush-mode: on_save # Sessions flush mode.
    port: ${redis_port}
    host: ${redis_host}
    password: ${redis_pwd}
    username: ${redis_user}