apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-configmap
data:
  apiGatewayUrl: http://e-commerce-gateway:9080
  priceUrl: http://product-price:9082
  sellerUrl: http://product-seller:9083
  productUrl: http://product:9081
  zipKinUrl: http://jaeger.logging:9411
  dbUrl: jdbc:mysql://mysql:3306/ecommerce?createDatabaseIfNotExist=true
  dbName: ecommerce
  appProfile: prod