apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-configmap
data:
  apigatewayUrl: http://e-commerce-gateway-service:9080/
  priceUrl: http://product-price-service:9082/productPrice/product
  sellerUrl: http://product-seller-service:9083/productSeller/product
  productUrl: http://product-service:9081/products