apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-configmap
data:
  apiGatewayUrl: http://e-commerce-gateway:9080
  priceUrl: http://product-price:9082
  sellerUrl: http://product-seller:9083
  productUrl: http://product:9081
  zipKinUrl: http://jaeger.logging:9411

  productDbUrl: jdbc:mysql://mysql:3306/product?createDatabaseIfNotExist=true
  productDb: product

  productSellerDbUrl: jdbc:mysql://mysql:3306/product_seller?createDatabaseIfNotExist=true
  productSellerDb: product_seller

  productPriceDbUrl: jdbc:mysql://mysql:3306/product_price?createDatabaseIfNotExist=true
  productPriceDb: product_price    
      
  appProfile: prod