apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  # namespace: eks-example
  labels:
    app: product
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce-ang
  template:
    metadata:
      labels:
        app: e-commerce-ang
    spec:
      containers:
      - name: e-commerce-ang
        image: {{ .Values.e_commerce_ang.image }}:{{ .Values.version }}
        env: 
        - name: api_gateway_url
          valueFrom:
            configMapKeyRef: 
              name: e-commerce-configmap
              key: apiGatewayUrl         
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: actuator/health
            port: http
        readinessProbe:
          httpGet:
            path: actuator/health
            port: http