apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.product_price.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.product_price.name }}
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.product_price.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.product_price.name }}
    spec:
      containers:
      - name: {{ .Values.product_price.name }}
        image: {{ .Values.product_price.image }}:{{ .Values.version }}
        env:
          - name: zipkin_url
            valueFrom:
              configMapKeyRef: 
                name: e-commerce-configmap
                key: zipKinUrl              
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 9082
          name: http
          protocol: TCP