apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProductSeller
  # namespace: eks-example
  labels:
    app: ProductSeller
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProductSeller
  template:
    metadata:
      labels:
        app: ProductSeller
    spec:
      containers:
      - name: ProductSeller
        image: {{ .Values.ProductSeller.image }}:{{ .Values.version }}
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 9083
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: actuator/health
            port: http
        readinessProbe:
          httpGet:
            path: actuator/health
            port: http