apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.product_seller.name }}
  namespace: {{ .Values.namespace }}
  # namespace: eks-example
  labels:
    app: {{ .Values.product_seller.name }}
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    #flux.weave.works/ignore: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.product_seller.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.product_seller.name }}
    spec:
      containers:
      - name: {{ .Values.product_seller.name }}
        image: {{ .Values.product_seller.image }}:{{ .Values.version }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
 {{ if(default .Values.enableProbes) }}               
        readinessProbe:
          httpGet:
            port: {{ .Values.product_seller.port }}
            path: {{ .Values.readinessUrl }}              
        livenessProbe:
          httpGet:
            port: {{ .Values.product_seller.port }}
            path: {{ .Values.livenessUrl }}    
    {{ end}}                              
        env:
          - name: zipkin_url
            valueFrom:
              configMapKeyRef: 
                name: e-commerce-configmap
                key: zipKinUrl            
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.product_seller.port }}
          name: http
          protocol: TCP