# Release-wide Values
replicas: 1
version: "latest"
namespace: logging

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Service Specific Values
fluentd:
  name: fluentd
  image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
elastic_search:
  name: elastic-search
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
kibana:
  name: kibana
  image: docker.elastic.co/kibana/kibana:7.6.2
jaeger:
  name: jaeger
  image: jaegertracing/all-in-one:1.40

ingress:
  - name: elastic-search
    replicaCount: 1
    annotations:
      class: nginx
    hosts:
      - paths:
          - path: /elastic-search
            backend:
              serviceName: elastic-search
              servicePort: 9200
  - name: kibana
    replicaCount: 1
    annotations:
      class: nginx
    hosts:
      - paths:
          - path: /kibana
            backend:
              serviceName: kibana
              servicePort: 5601

  - name: jaeger
    replicaCount: 1
    annotations:
      class: nginx
    hosts:
      - paths:
          - path: /jaeger
            backend:
              serviceName: jaeger
              servicePort: 16686
