apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector: 
    app: {{ .Values.grafana.name }}
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 32000