apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grafana.name }}
  template:
    metadata:
      name: {{ .Values.grafana.name }}
      labels:
        app: {{ .Values.grafana.name }}
    spec:
      containers:
        - name: {{ .Values.grafana.name }}
          image: {{ .Values.grafana.image }}
          ports:
            - name: {{ .Values.grafana.name }}
              containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: pvc-monitoring-storage
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
        - name: ge-config
          configMap:
            defaultMode: 420
            name: ge-config            
