apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-monitoring-storage
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi