apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-logging-map
  # namespace: {{ .Values.namespace }} 
data:
  fluentEsHost: elastic-search.logging
  fluentEsPort: '9200'
  fluentEsScheme: http
  fluentEsUser: elastic
  fluentEsPwd: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-logging-map
  namespace: {{ .Values.namespace }} 
data:
  kibanaEsUrls: '["http://elastic-search:9200"]'