apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-logging-map
  namespace: kube-system 
data:
  fluentEsHost: elastic-search.logging
  fluentEsPort: '9200'
  fluentEsScheme: http
  fluentEsUser: elastic
  fluentEsPwd: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: e-commerce-logging-map
  namespace: {{ .Values.namespace }} 
data:
  kibanaEsUrls: '["http://elastic-search:9200"]'
  esServerUrls: http://elastic-search:9200
  kibanaServerBasePath: /kibana
  # kibanaServerPublicBaseUrl: ec2-44-204-225-244.compute-1.amazonaws.com/kibana 