server:
  port: 9080
  shutdown: GRACEFUL
spring:
  application:
    name: e-commerce-gateway-service
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
  sleuth:
    opentracing:
      enabled: true
  zipkin:
    base-url: ${zipkin_url}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
#          gateway: TRACE


#open docs
springdoc:
  api-docs:
    path: /api-docs


#actuator
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
product:
  app:
    priceUrl: ${price_url}
    sellerUrl: ${seller_url}
    productUrl: ${product_url}
