server:
  port: 9080
  shutdown: GRACEFUL
spring:
  application:
    name: e-commerce-gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # Replace with the domain of your Auth0 tenant.
          # Note the trailing slash is important!
          issuer-uri: ${jwt_issuer_uri}
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
  sleuth:
    opentracing:
      enabled: true
  zipkin:
    base-url: ${zipkin_url}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          #          gateway: INFO
          gateway: TRACE

resilience4j:
  circuitbreaker:
    instances:
      product:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
      price:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
      seller:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
      user:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
      cart:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true
  timelimiter:
    instances:
      product:
        timeoutDuration: 4s
      price:
        timeoutDuration: 4s
      seller:
        timeoutDuration: 4s
      user:
        timeoutDuration: 4s
      cart:
        timeoutDuration: 4s


#open docs
springdoc:
  api-docs:
    path: /api-docs


#actuator
management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

auth0:
  audience: ${audience_id}


product:
  app:
    priceUrl: ${price_url}
    sellerUrl: ${seller_url}
    productUrl: ${product_url}
    userUrl: ${user_url}
    cartItemsUrl: ${cart_items_url}
    enableSecurity: ${enable_security}
